#if (MC_VERSION >= 11800 || MC_VERSION == 11605) && defined IS_IRIS
	#define MODERN_BACKEND
#endif



// optifine settings (DON'T DELETE)
/*
const int   colortex0Format       = RGB10_A2;
const bool  colortex0Clear        = false;
const int   colortex1Format       = RGB10_A2;
const bool  colortex1Clear        = false;
const int   colortex2Format       = RGBA16;
#ifndef VOXY
	const bool  colortex2Clear    = true;
#endif
const int   colortex3Format       = RGBA16;
const bool  colortex3Clear        = true;
const int   colortex4Format       = R11F_G11F_B10F;
const bool  colortex4Clear        = false;
const int   colortex5Format       = RGB10_A2;
const bool  colortex5Clear        = true;
const int   colortex6Format       = RG16;
const bool  colortex6Clear        = false;
const int   colortex7Format       = R16;
const bool  colortex7Clear        = false;
#ifdef VOXY
	const int   colortex8Format   = RGBA8;
	const bool  colortex8Clear    = true;
#endif
const bool  shadowtex0Clear       = false;
const bool  shadowtex1Clear       = false;
const float wetnessHalflife       = 30.0f;
const float drynessHalflife       = 30.0f;
const float eyeBrightnessHalflife = 4.0f;
const float ambientOcclusionLevel = 1.0;
const float shadowIntervalSize    = 2.0;
#if COLORED_LIGHTING_ENABLED == 1
	const float voxelDistance = 32.0;
#endif
*/





// settings basics

#include "/basics/setting_defines.glsl"

#if STYLE == 0
	#include "/style_vanilla.glsl"
#endif
#if STYLE == 1
	#include "/style_fantasy.glsl"
#endif
#if STYLE == 2
	#include "/style_realistic.glsl"
#endif
#if STYLE == 3
	#include "/style_cartoon.glsl"
#endif





// post-processed definitions

#ifdef NETHER
	#undef DEPTH_SUNRAYS_ENABLED
	#define DEPTH_SUNRAYS_ENABLED 0
	#undef VOL_SUNRAYS_ENABLED
	#define VOL_SUNRAYS_ENABLED 0
	#undef HEIGHT_BASED_WAVING_ENABLED
	#define HEIGHT_BASED_WAVING_ENABLED 0
#endif

#ifdef END
	#undef DEPTH_SUNRAYS_ENABLED
	#define DEPTH_SUNRAYS_ENABLED 0
	#undef VOL_SUNRAYS_ENABLED
	#define VOL_SUNRAYS_ENABLED 0
	#undef WAVING_ENABLED
	#define WAVING_ENABLED 0
	#undef PHYSICALLY_WAVING_WATER_ENABLED
	#define PHYSICALLY_WAVING_WATER_ENABLED 0
	#undef WAVING_WATER_SURFACE_ENABLED
	#define WAVING_WATER_SURFACE_ENABLED 0
#endif

#ifndef OVERWORLD
	#undef REALISTIC_CLOUDS_ENABLED
	#define REALISTIC_CLOUDS_ENABLED 0
#endif

#ifndef NETHER
	#undef NETHER_CLOUDS_ENABLED
	#define NETHER_CLOUDS_ENABLED 0
#endif

#ifndef END
	#undef END_CLOUDS_ENABLED
	#define END_CLOUDS_ENABLED 0
#endif

#if defined OVERWORLD && OVERWORLD_SHADOWS_ENABLED == 1
	#define SHADOWS_ENABLED
#endif
#if defined END && END_SHADOWS_ENABLED == 1
	#define SHADOWS_ENABLED
#endif



#ifndef SHADOWS_ENABLED
	#undef VOL_SUNRAYS_ENABLED
	#define VOL_SUNRAYS_ENABLED 0
#endif

#if KUWAHARA_ENABLED == 1
	#undef SHARPENING_ENABLED
	#define SHARPENING_ENABLED 0
#endif

#if defined DISTANT_HORIZONS || defined VOXY
	#undef BORDER_FOG_ENABLED
	#define BORDER_FOG_ENABLED 0
#endif

#if SSS_PIXELS != 0
	#undef TAA_ENABLED
	#defined TAA_ENABLED 0
	#undef FXAA_ENABLED
	#defined FXAA_ENABLED 0
	#undef SHARPENING_ENABLED
	#defined SHARPENING_ENABLED 0
#endif

#if TEMPORAL_FILTER_ENABLED == 0
	#undef TAA_ENABLED
	#define TAA_ENABLED 0
#endif

#if ISOMETRIC_RENDERING_ENABLED == 1
	#undef BORDER_FOG_ENABLED
	#define BORDER_FOG_ENABLED 0
#endif

#if PBR_TYPE == 1
	#undef EMISSIVE_TEXTURES_ENABLED
	#define EMISSIVE_TEXTURES_ENABLED 0
#endif

#if CLOUD_COMPATIBILITY == 2
	#undef CLOUD_COMPATIBILITY
	#if MODERN_BACKEND
		#define CLOUD_COMPATIBILITY 0
	#else
		#define CLOUD_COMPATIBILITY 1
	#endif
#endif
#undef CLOUD_COMPATIBILITY
#define CLOUD_COMPATIBILITY 1



#if (defined OVERWORLD && CUSTOM_OVERWORLD_SKYBOX == 1) || (defined NETHER && CUSTOM_NETHER_SKYBOX == 1) || (defined END && CUSTOM_END_SKYBOX == 1)
	#define CUSTOM_SKYBOX
#endif



// How on earth can optifine be THIS bad???
#if TEMPORAL_FILTER_ENABLED == 1
	#undef TEMPORAL_FILTER_ENABLED
	#define TEMPORAL_FILTER_ENABLED 1
#endif
#if SSS_PHOSPHOR == 1
	#undef SSS_PHOSPHOR
	#define SSS_PHOSPHOR 1
#endif
#if MOTION_BLUR_ENABLED == 1
	#undef MOTION_BLUR_ENABLED
	#define MOTION_BLUR_ENABLED 1
#endif



#define BLOCK_COLOR vec3(BLOCK_RED, BLOCK_GREEN, BLOCK_BLUE) * BLOCK_BRIGHTNESS
#define CAVE_AMBIENT_COLOR vec3(CAVE_AMBIENT_RED, CAVE_AMBIENT_GREEN, CAVE_AMBIENT_BLUE) * CAVE_AMBIENT_BRIGHTNESS
#define NETHER_AMBIENT_COLOR vec3(NETHER_AMBIENT_RED, NETHER_AMBIENT_GREEN, NETHER_AMBIENT_BLUE) * NETHER_AMBIENT_BRIGHTNESS;
#define NETHER_BLOCKLIGHT_MULT vec3(NETHER_BLOCKLIGHT_RED_MULT, NETHER_BLOCKLIGHT_GREEN_MULT, NETHER_BLOCKLIGHT_BLUE_MULT) * NETHER_BLOCKLIGHT_BRIGHTNESS_MULT
#define END_SKYLIGHT_COLOR vec3(END_SKYLIGHT_RED, END_SKYLIGHT_GREEN, END_SKYLIGHT_BLUE) * END_SKYLIGHT_BRIGHTNESS
#define END_AMBIENT_COLOR vec3(END_AMBIENT_RED, END_AMBIENT_GREEN, END_AMBIENT_BLUE) * END_AMBIENT_BRIGHTNESS
#define WATER_COLOR vec3(WATER_COLOR_RED, WATER_COLOR_GREEN, WATER_COLOR_BLUE)

#define SKYLIGHT_DAY_COLOR vec3(SKYLIGHT_DAY_RED, SKYLIGHT_DAY_GREEN, SKYLIGHT_DAY_BLUE) * SKYLIGHT_DAY_BRIGHTNESS
#define AMBIENT_DAY_COLOR vec3(AMBIENT_DAY_RED, AMBIENT_DAY_GREEN, AMBIENT_DAY_BLUE) * AMBIENT_DAY_BRIGHTNESS

#define SKYLIGHT_NIGHT_COLOR vec3(SKYLIGHT_NIGHT_RED, SKYLIGHT_NIGHT_GREEN, SKYLIGHT_NIGHT_BLUE) * SKYLIGHT_NIGHT_BRIGHTNESS
#define AMBIENT_NIGHT_COLOR vec3(AMBIENT_NIGHT_RED, AMBIENT_NIGHT_GREEN, AMBIENT_NIGHT_BLUE) * AMBIENT_NIGHT_BRIGHTNESS

#define SKYLIGHT_SUNRISE_COLOR vec3(SKYLIGHT_SUNRISE_RED, SKYLIGHT_SUNRISE_GREEN, SKYLIGHT_SUNRISE_BLUE) * SKYLIGHT_SUNRISE_BRIGHTNESS
#define AMBIENT_SUNRISE_COLOR vec3(AMBIENT_SUNRISE_RED, AMBIENT_SUNRISE_GREEN, AMBIENT_SUNRISE_BLUE) * AMBIENT_SUNRISE_BRIGHTNESS

#define SKYLIGHT_SUNSET_COLOR vec3(SKYLIGHT_SUNSET_RED, SKYLIGHT_SUNSET_GREEN, SKYLIGHT_SUNSET_BLUE) * SKYLIGHT_SUNSET_BRIGHTNESS
#define AMBIENT_SUNSET_COLOR vec3(AMBIENT_SUNSET_RED, AMBIENT_SUNSET_GREEN, AMBIENT_SUNSET_BLUE) * AMBIENT_SUNSET_BRIGHTNESS

#define ATMOSPHERIC_FOG_DAY vec3(ATMOSPHERIC_FOG_DAY_RED, ATMOSPHERIC_FOG_DAY_GREEN, ATMOSPHERIC_FOG_DAY_BLUE)
#define ATMOSPHERIC_FOG_NIGHT vec3(ATMOSPHERIC_FOG_NIGHT_RED, ATMOSPHERIC_FOG_NIGHT_GREEN, ATMOSPHERIC_FOG_NIGHT_BLUE)
#define ATMOSPHERIC_FOG_SUNRISE vec3(ATMOSPHERIC_FOG_SUNRISE_RED, ATMOSPHERIC_FOG_SUNRISE_GREEN, ATMOSPHERIC_FOG_SUNRISE_BLUE)
#define ATMOSPHERIC_FOG_SUNSET vec3(ATMOSPHERIC_FOG_SUNSET_RED, ATMOSPHERIC_FOG_SUNSET_GREEN, ATMOSPHERIC_FOG_SUNSET_BLUE)

#define SUNRAYS_SUN_COLOR vec3(SUNRAYS_SUN_RED, SUNRAYS_SUN_GREEN, SUNRAYS_SUN_BLUE)
#define SUNRAYS_MOON_COLOR vec3(SUNRAYS_MOON_RED, SUNRAYS_MOON_GREEN, SUNRAYS_MOON_BLUE)

#define SKY_DAY_COLOR (vec3(SKY_DAY_RED, SKY_DAY_GREEN, SKY_DAY_BLUE) * SKY_DAY_BRIGHTNESS)
#define SKY_NIGHT_COLOR (vec3(SKY_NIGHT_RED, SKY_NIGHT_GREEN, SKY_NIGHT_BLUE) * SKY_NIGHT_BRIGHTNESS)
#define SKY_HORIZON_DAY_COLOR (vec3(SKY_HORIZON_DAY_RED, SKY_HORIZON_DAY_GREEN, SKY_HORIZON_DAY_BLUE) * SKY_HORIZON_DAY_BRIGHTNESS)
#define SKY_HORIZON_NIGHT_COLOR (vec3(SKY_HORIZON_NIGHT_RED, SKY_HORIZON_NIGHT_GREEN, SKY_HORIZON_NIGHT_BLUE) * SKY_HORIZON_NIGHT_BRIGHTNESS)
#define SKY_HORIZON_SUNRISE_COLOR (vec3(SKY_HORIZON_SUNRISE_RED, SKY_HORIZON_SUNRISE_GREEN, SKY_HORIZON_SUNRISE_BLUE) * SKY_HORIZON_SUNRISE_BRIGHTNESS)
#define SKY_HORIZON_SUNSET_COLOR (vec3(SKY_HORIZON_SUNSET_RED, SKY_HORIZON_SUNSET_GREEN, SKY_HORIZON_SUNSET_BLUE) * SKY_HORIZON_SUNSET_BRIGHTNESS)

#define NETHER_SKY_BASE_COLOR vec3(NETHER_SKY_BASE_RED, NETHER_SKY_BASE_GREEN, NETHER_SKY_BASE_BLUE)

#define END_SKY_COLOR vec3(END_SKY_RED, END_SKY_GREEN, END_SKY_BLUE)
#define END_STATIC_COLOR vec3(END_STATIC_RED, END_STATIC_GREEN, END_STATIC_BLUE)

#define CLOUD_DAY_COLOR vec3(CLOUD_DAY_RED, CLOUD_DAY_GREEN, CLOUD_DAY_BLUE)
#define CLOUD_NIGHT_COLOR vec3(CLOUD_NIGHT_RED, CLOUD_NIGHT_GREEN, CLOUD_NIGHT_BLUE)
#define CLOUD_SUNRISE_COLOR vec3(CLOUD_SUNRISE_RED, CLOUD_SUNRISE_GREEN, CLOUD_SUNRISE_BLUE)
#define CLOUD_SUNSET_COLOR vec3(CLOUD_SUNSET_RED, CLOUD_SUNSET_GREEN, CLOUD_SUNSET_BLUE)
#define CLOUD_BOTTOM_TINT vec3(CLOUD_BOTTOM_TINT_RED, CLOUD_BOTTOM_TINT_GREEN, CLOUD_BOTTOM_TINT_BLUE)
#define CLOUD_WEATHER_TINT vec3(CLOUD_WEATHER_TINT_RED, CLOUD_WEATHER_TINT_GREEN, CLOUD_WEATHER_TINT_BLUE)

#define NETHER_CLOUDS_BASE_COLOR vec3(NETHER_CLOUDS_BASE_RED, NETHER_CLOUDS_BASE_GREEN, NETHER_CLOUDS_BASE_BLUE)

#define END_CLOUDS_DARK_COLOR vec3(END_CLOUDS_RED_DARK, END_CLOUDS_GREEN_DARK, END_CLOUDS_BLUE_DARK)
#define END_CLOUDS_BRIGHT_COLOR vec3(END_CLOUDS_RED_BRIGHT, END_CLOUDS_GREEN_BRIGHT, END_CLOUDS_BLUE_BRIGHT)

#define WATER_FOG_COLOR vec3(WATER_FOG_RED, WATER_FOG_GREEN, WATER_FOG_BLUE)
#define LAVA_FOG_COLOR vec3(LAVA_FOG_RED, LAVA_FOG_GREEN, LAVA_FOG_BLUE)
#define POWDERED_SNOW_FOG_COLOR vec3(POWDERED_SNOW_FOG_RED, POWDERED_SNOW_FOG_GREEN, POWDERED_SNOW_FOG_BLUE)

#ifdef OVERWORLD
	#define GLOWING_ORES_STRENGTH GLOWING_ORES_STRENGTH_OVERWORLD
#elif defined NETHER
	#define GLOWING_ORES_STRENGTH GLOWING_ORES_STRENGTH_NETHER
#elif defined END
	#define GLOWING_ORES_STRENGTH GLOWING_ORES_STRENGTH_END
#endif



// settings won't show up unless they're actually used in glsl code
#if PLAYER_SHADOWS_ENABLED == 1
#endif
#if ENTITY_SHADOWS_ENABLED == 1
#endif
#if BLOCK_ENTITY_SHADOWS_ENABLED == 1
#endif
